language: php
sudo: false

matrix:
  include:
    - php: "7.4"
      env:
        - LARAVEL_VERSION=^8.0
    - php: "8.0snapshot"
      env:
        - LARAVEL_VERSION=^8.0

install:
  - composer require "illuminate/contracts:${LARAVEL_VERSION}" --no-update -n
  - composer require "illuminate/http:${LARAVEL_VERSION}" --no-update -n
  - composer require "illuminate/support:${LARAVEL_VERSION}" --no-update -n
  - travis_retry composer install --no-suggest --prefer-dist -n -o

script:
  - vendor/bin/phpunit
